ext {
    extName = '3D Porn Dude'
    extClass = '.PornDude'
    baseUrl = 'https://3dporndude.com'
    extVersionCode = 1
    isNsfw = true
}

apply plugin: "kei.plugins.extension.legacy"

dependencies {
    // Dependência da API do Aniyomi (contém AnimeHttpSource, SAnime, etc.)
    implementation("eu.kanade.tachiyomi.animesource:api:1.0.7")
    // Caso queira manter também a dependência do core (opcional)
    // implementation(project(":core"))
}
