name: Build and Push Repo

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build CosXplay Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Apply Spotless Formatting
        run: ./gradlew spotlessApply

      - name: Build CosXplay APK
        run: ./gradlew :src:pt:cosxplay:assembleRelease

      - name: Create Multimodule Index
        run: ./gradlew createMultimoduleIndex

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cosxplay-apk
          path: "**/*.apk"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repo
